//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InputsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.Comments = new HashSet<Comments>();
            this.Review = new HashSet<Review>();
            this.Comments1 = new HashSet<Comments>();
            this.Shelves = new HashSet<Shelves>();
        }
    
        public int id { get; set; }
        public string TItle { get; set; }
        public string Description { get; set; }
        public int AuthorID { get; set; }
        public int Rating { get; set; }
        public int CategoryID { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<Review> Review { get; set; }
        public virtual ICollection<Comments> Comments1 { get; set; }
        public virtual ICollection<Shelves> Shelves { get; set; }
    }
}
