//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InputsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Comments = new HashSet<Comments>();
            this.Review = new HashSet<Review>();
            this.Shelves = new HashSet<Shelves>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string AuthCode { get; set; }
        public string sessionKey { get; set; }
        public bool IsEditor { get; set; }
        public bool IsAuthor { get; set; }
    
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<Review> Review { get; set; }
        public virtual ICollection<Shelves> Shelves { get; set; }
    }
}
