//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Comments = new HashSet<Comment>();
            this.Reviews = new HashSet<Review>();
            this.Shelves = new HashSet<Shelf>();
        }
    
        public int id { get; set; }
        public string TItle { get; set; }
        public string Description { get; set; }
        public int AuthorID { get; set; }
        public int Rating { get; set; }
        public int CategoryID { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<Shelf> Shelves { get; set; }
    }
}
