//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Reviews = new HashSet<Review>();
            this.Shelves = new HashSet<Shelf>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string AuthCode { get; set; }
        public string sessionKey { get; set; }
        public bool IsEditor { get; set; }
        public bool IsAuthor { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<Shelf> Shelves { get; set; }
    }
}
